inherit_gem:
  rubocop-rails-omakase: rubocop.yml

# Overwrite or add rules to create your own house style
# Example: Disable space inside array literal brackets rule
Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false